spring.application.name=day1-foundations-workshop

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

logging.level.root=INFO
logging.level.com.nashtech.observability=DEBUG

app.simulation.min-delay-ms=150
app.simulation.max-delay-ms=900
app.simulation.error-rate=0.30
