spring.application.name=day1-foundations-workshop

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging.level.root=INFO
logging.level.com.nashtech.observability=DEBUG

app.simulation.min-delay-ms=150
app.simulation.max-delay-ms=900
app.simulation.error-rate=0.30
